language: node_js
node_js:
  - node
  - lts/*
cache:
  yarn: true
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
script:
  - yarn install
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - yarn install
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
